# A2LiX Translation Form
a2lix_translation_form:
  locale_provider: default
  default_locale: '%locale%'
  locales: '%locales%'
  required_locales: '%locale%'
  templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"